### ISSUE TITLE
Support INDI devices

### ISSUE THREAD

**Issue by ckuethe** [cbassa/stvid#36]
INDI already support ZWO ASI cameras, along with many others. This would be useful for other camera types that are supported by INDI but not by CV2.

I just started tinking with this.

**Comment by cbassa** [comment]
Great! For now it may be best to implement this as a separate function (e.g. `capture_indi`), as I'm not sure all ZWO ASI functionality is offered through INDI.

**Comment by ckuethe** [comment]
That was my plan exactly. If not exactly the same controls, a large subset of the most useful ones are available...

**Comment by ckuethe** [comment]
https://github.com/GuLinux/AstroPhoto-Plus looks like a nifty bit of inspiration.

**Comment by ckuethe** [comment]
crossposting to thomasjacquin/allsky#112

Here are a few repos I found last night while looking for python INDI examples. Some of these may be more useful than others for figuring out how to use the [python API](https://github.com/geehalel/pyindi-client)... Not at all looking forward to figuring out how to do this in C++

* https://github.com/teuben/pyASC
* https://github.com/zemogle/pyOculus
* https://github.com/LowellObservatory/All-Sky
* https://github.com/farom57/Orbit-hunter
* https://github.com/oleg-milantiev/allsky.py
* https://github.com/TomMladenov/indi-viewer

**Comment by cbassa** [comment]
I'm closing this for now as the last time I checked, the INDI plugin for ASI cameras could not operate the cameras at the required frame rates (too slow).
