### ISSUE TITLE
Make the ASI reader check for unsupported frame sizes

### ISSUE THREAD

**Issue by ckuethe** [cbassa/stvid#40]
The default config specifies 1544x1040, my camera only goes up to 1280x960. It would be good for the ASI reader to check that the user has specified a supported frame size.

While I'm thinking about it, would it be worth adding some good default behavior, eg. use the largest supported frame size?

**Comment by cbassa** [comment]
These parameters are camera specific, and it requires some testing to find the best binning factor and exposure time/frame rate. Hence, using the largest supported frame size is not always the best option.

It would be nice to only have to specify the binning factor in the config file, and then let the camera return the resolution it can run at, but it means initializing the camera outside of the capture functions. It's not the cleanest solution in my opinion...

**Comment by ckuethe** [comment]
No worries, this was more of a "hey, what do you think about this?" kind of PR. On that note, do you prefer lots of little single-change PRs or can I mash a few commits together?

**Comment by interplanetarychris** [comment]
I've added some exception handling in PR https://github.com/cbassa/stvid/pull/43, although I would like to update acquire.py to query the camera directly for nx,ny and auto-compute frames sizes based on binning.
