### ISSUE TITLE
Add capability for stvid to estimate visual magnitude

### ISSUE THREAD

**Issue by interplanetarychris** [cbassa/stvid#51]
It would be a killer feature if, in the process of cataloging, centroiding and line-fitting satellite observations, if astrometry.py or stars.py could be augmented to estimate the visual magnitude of a single frame, or series of satobs within a fourframe.

**Comment by cbassa** [comment]
Measuring magnitudes from stvid observations is very high on my wish list. Unfortunately, the way the data is stored in the four frames makes it very hard to extract reliable magnitudes. It is a problem I've banged my head against for a few years now. I think I know a method that may work, but it will require testing to determine its reliability.
