### ISSUE TITLE
Provide parameter/method to filter out overlapping IODs

### ISSUE THREAD

**Issue by interplanetarychris** [cbassa/stvid#53]
`(extract.py?)` occasionally finds a satellite solution for a short track on-top of a long track.  These cases are unlikely, and it may be possible to prevent an IOD from being registered if the short track is known to be on-top/parallel of a long-track in the same-solved frame.  The long-track is more likely the valid solution.

**Comment by cbassa** [comment]
Solved with updated processing method.
