### ISSUE TITLE
Add available keywords to FITS headers (convenience)

### ISSUE THREAD

**Issue by interplanetarychris** [cbassa/stvid#61]
In the acquire/calibrate/process flow, add available known values to the FITS files (in satobs, or results folders, as appropriate) where convenient.

Some of these might require config keywords, others might be derived from camera drivers, sextractor/astrometry.net or other calculation.

Potential list of items (derived from INDI/Ekos example imaging)
- [ ] BITPIX : number of bits per data pixel (e.g. 16)
- [ ] INSTRUME : CCD Name (e.g. 'ZWO CCD ASI294MC Pro')
- [ ] TELESCOP : Telescope name (might need to add a keyword to config file)
- [ ] CCD-TEMP : Sensor temp (Celcius)
- [ ] PIXSIZE1 : Pixel Size 1 (microns)
- [ ] PIXSIZE2 : Pixel Size 2 (microns)
- [ ] XBINNING : Binning factor in width (e.g. 3)
- [ ] YBINNING : Binning factor in height (e.g. 3)
- [ ] XPIXSZ : Pixel size including binning, X-axis (um)
- [ ] YPIXSZ : Pixel size including binning, Y-axis (um)
- [ ] FOCALLEN : Focal length (mm)
- [ ] APTDIA : Telescope diameter (mm)
- [ ] SCALE : arcsecs per pixel
- [ ] GAIN: Sensor Gain
- [ ] Offset: Sensor Offset
- [ ] OBSGEO-L : Geodetic longitude of observation location (deg)
- [ ] LONG-OBS : Geodetic longitude (deg) (compatibility)
- [ ] OBSGEO-B : Geodetic latitude of observation location (deg)
- [ ] LAT-OBS : Geodetic latitude (deg) (compatibility)

**Comment by cbassa** [comment]
Some thoughts about implementing this.

BITPIX is included, as it comes with the data.

A few of these should be specified in the configuration file, which means it is up to the user to ensure that these are correct. This is a bit tricky, as there is nothing more annoying that metadata which is wrong; it would be better to have it absent in that case.

For ASI cameras the CCD parameters can be gotten from the camera when it is initialized, though that is currently compilcated as the cameras are initialized within the capture thread, and hence the information would need to be moved between the capture and compress threads. Perhaps a `manager` would work here (https://docs.python.org/3/library/multiprocessing.html#sharing-state-between-processes), though we could also try to move camera initialization to the main thread, which could help with #40.

**Comment by ckuethe** [comment]
It looks like there are some tools that can manipulate FITS headers the way id3tag (et al.) can do for mp3 files. Would batch-editing some of the headers after a capture session be at all useful?

**Comment by cbassa** [comment]
Perhaps only for backwards compatibility. Of the parameters that @interplanetarychris suggests only the observing location parameters can actually be used if a site code is absent. The rest is more for information.

**Comment by cbassa** [comment]
Added site information in https://github.com/cbassa/stvid/commit/5497433078bcab530377c3de31bd250dadd2c442
