### ISSUE TITLE
"acquire" from existing FITS

### ISSUE THREAD

**Issue by mgrutten** [cbassa/stvid#66]
I have a set of FITS files that I'd like to process with STVID.  As far as I can tell that isn't possible at the moment?
Would it be possible to create a FITS "camera" that loads from a sequence of files, rather than doing a live capture?

**Comment by cbassa** [comment]
Yes, it is possible to write a tool to combine a sequence of FITS files (or any image format) into the FITS files that STVID can read. For STVID to process the resulting files and produce sensible results, the timestamps of the individual frames need to be reasonably accurate and the satellites should not trail significantly within the individual exposures.

**Comment by mgrutten** [comment]
Great!  Thanks for the quick response.
I started hacking something to take a fits, based on the compress function in "acquire".  In hindsight it's obvious from your comment, but I've realised that I have the wrong type of data.  I have long exposures (30s, staring in a fixed direction for GEO).
If I set zmax and zavg as the (single) frame data, znum and zstd as zeros, will "process" do something sensible, or am I out of luck?

**Comment by cbassa** [comment]
Unfortunately the `znum` and `zstd` frames are required for the processing to work, as the algorithm is designed for satellites that move fast through the field-of-view. Hence, this kind of data for geostationary satellites will not work with stvid.

My sattools repo (https://github.com/cbassa/sattools) has functionality for analyzing this kind of data, so you can try that out. Send me an email if you have questions, as it has a quite steep learning curve.

**Comment by mgrutten** [comment]
Email sent and challenge accepted!  Thanks!
